apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dilshad
  name: dilshad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dilshad
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dilshad
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
