apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dilshad
  name: dilshad
spec:
  replicas: 5
  selector:
    matchLabels:
      app: dilshad
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dilshad
    spec:
      containers:
      - image: nginx:1.9.7
        name: nginx
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dilshad
  name: dilshad
spec:
  ports:
  - name: dilshad
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: dilshad
  type: ClusterIP
status:
  loadBalancer: {}
