apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: dilshad
  name: dilshad
spec:
  containers:
  - image: nginx
    name: dilshad
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
